#!/bin/bash
# .binder/postBuild

set -e

# Install guile-simple-zmq from source
git clone https://github.com/jerry40/guile-simple-zmq.git
cd guile-simple-zmq
autoreconf -vif
./configure
make
sudo make install
cd ..

# Install the jupyter guile kernel from source
pip install jupyter-guile-kernel